services:
  traefik:
    container_name: traefik
    image: traefik:v3.6
    restart: unless-stopped
    environment:
      - CLOUDFLARE_EMAIL=${CF_API_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CLOUDFLARE_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN}
    command:
      # Traefik settings
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      # Docker provider settings
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Entrypoints settings
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=$CLOUDFLARE_IPS,$LOCAL_IPS,$TAILSCALE_IPS
      # ACME settings
      # - "--certificatesResolvers.cfResolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # LetsEncrypt Staging Server - uncomment when testing
      - "--certificatesresolvers.cfResolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cfResolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cfResolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.cfResolver.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      # - "--certificatesresolvers.cfResolver.acme.dnschallenge.propagation.delaybeforechecks=120"
      # Cert resolver and domains
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=cfResolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=ts.krokosik.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.ts.krokosik.com"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.ts.krokosik.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=cfResolver"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.docker.network=krokosik-web-services"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - krokosik-web-services

networks:
  krokosik-web-services:
    external: true
